FROM semcon/sc-base
MAINTAINER "Christoph Fabianek" christoph@ownyourdata.eu

COPY . .
COPY docker/oyd-databud.config.json_issuer public/config/oyd-databud.config.json
RUN bundle install

CMD ["./script/run.sh"]

EXPOSE 3000 3000